#!/bin/sh
# /etc/init.d/tightvncserver
# Thanks to Neil Black at www.neil-black.co.uk/raspberry-pi-beginners-guide
VNCUSER='pi'
case "$1" in
   start)
      su $VNCUSER -c '/usr/bin/tightvncserver :1'
      echo "Starting TightVNC Server for $VNCUSER "
      ;;
   stop)
      pkill Xtightvnc
      echo "TightVNC Server stopped"
      ;;
   *)
      echo "Usage: /etc/init.d/tightvncserver {start|stop}"
      exit 1
      ;;
esac
exit 0

